repositories {
    mavenCentral()
    google()
    maven { url = "https://mymaven.bylazar.com/releases" }
    maven { url = 'https://maven.brott.dev/' }
    // Repository for SolversLib
    maven { url = "https://repo.dairy.foundation/releases" }
}

dependencies {
    // FTC SDK Core
    implementation 'org.firstinspires.ftc:Inspection:11.0.0'
    implementation 'org.firstinspires.ftc:Blocks:11.0.0'
    implementation 'org.firstinspires.ftc:RobotCore:11.0.0'
    implementation 'org.firstinspires.ftc:RobotServer:11.0.0'
    implementation 'org.firstinspires.ftc:OnBotJava:11.0.0'
    implementation 'org.firstinspires.ftc:Hardware:11.0.0'
    implementation 'org.firstinspires.ftc:FtcCommon:11.0.0'
    implementation 'org.firstinspires.ftc:Vision:11.0.0'

    // Android Support
    implementation 'androidx.appcompat:appcompat:1.2.0'

    // Dashboard
    implementation 'com.acmerobotics.dashboard:dashboard:0.5.1'

    // Pedro Pathing & Utilities
    implementation 'com.pedropathing:ftc:2.0.6'
    implementation 'com.pedropathing:telemetry:1.0.0'
    implementation 'com.bylazar:fullpanels:1.0.10'

    // SolversLib (Core + Pedro Pathing Integration)
    implementation "org.solverslib:core:0.3.3"
    implementation "org.solverslib:pedroPathing:0.3.3"
}